# Documentation:  http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - nightly
notifications:
  email: false
git:
  depth: 99999999
  
## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
## NEEDED as Nemo.jl is not v0.7 ready, so cannot be found
matrix:
  allow_failures:
    - julia: nightly

#script: # the default script is equivalent to the following
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Example"); Pkg.test("Example"; coverage=true)';
after_success:
- julia -e 'cd(Pkg.dir("ArbNumerics")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
