name = "ArbNumerics"
uuid = "7e558dbc-694d-5a72-987c-6f4ebed21442"
repo = "https://github.com/JeffreySarnoff/ArbNumerics.jl.git"
author = "Jeffrey Sarnoff"
license = "MIT"
version = "v0.1.3"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
BinDeps = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Readables = "0d4725de-cd7c-5e44-8a85-a48caeef9fa5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
SpecialFunctions = ">=0.6.0"
BinDeps = ">=0.8.8"
Readables = ">=0.1.2"
